name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REGION: ${{ secrets.GCP_REGION }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REPOSITORY: notely-ar-repo
      IMAGE: notely
      TAG: ${{ github.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Verify goose installation
        run: goose --version

      - name: Build production binary
        run: ./scripts/buildprod.sh

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify gcloud installation
        run: gcloud info

      - name: Build and push Docker image
        run: gcloud builds submit --tag "$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$TAG" .

      - name: Run database migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image "$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$TAG" --region "$REGION" --allow-unauthenticated --project "$PROJECT_ID" --max-instances=4
